// The line icons available to Icon.svelte.
export type IconName =
  | "sun"
  | "moon"
  | "monitor"
  | "select-all"
  | "select-none"
  | "folder-open"
  | "download"
  | "trash"
  | "plus"
  | "save"
  | "restore"
  | "filter"
  | "calendar"
  | "chevron-down"
  | "sliders"
  | "contrast"
  | "volume-on"
  | "volume-off"
  | "zoom-in"
  | "zoom-out"
  | "close";
